<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-41G76H2" failures="1" tests="7" name="com.qa.test.REST_Assure_Get_Call" time="6.305" errors="0" timestamp="12 Mar 2019 10:47:53 GMT" skipped="0">
  <testcase classname="com.qa.test.REST_Assure_Get_Call" name="validate_get_incorrect_response_status_code" time="1.209"/>
  <testcase classname="com.qa.test.REST_Assure_Get_Call" name="validate_get_incorrect_response_status_line" time="0.574"/>
  <testcase classname="com.qa.test.REST_Assure_Get_Call" name="validate_response_headers_using_lamda_expression" time="0.575">
    <failure message="Header doesn&#039;t exists expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Header doesn't exists expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.qa.test.REST_Assure_Get_Call.lambda$validate_response_headers_using_lamda_expression$1(REST_Assure_Get_Call.java:73)
at java.base/java.lang.Iterable.forEach(Iterable.java:75)
at com.qa.test.REST_Assure_Get_Call.validate_response_headers_using_lamda_expression(REST_Assure_Get_Call.java:71)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
    </failure>
  </testcase> <!-- validate_response_headers_using_lamda_expression -->
  <testcase classname="com.qa.test.REST_Assure_Get_Call" name="validate_get_response_status_code" time="0.577"/>
  <testcase classname="com.qa.test.REST_Assure_Get_Call" name="validate_get_all_headers" time="0.609"/>
  <testcase classname="com.qa.test.REST_Assure_Get_Call" name="getResponseBody" time="2.179"/>
  <testcase classname="com.qa.test.REST_Assure_Get_Call" name="validate_get_response_status_line" time="0.582"/>
</testsuite> <!-- com.qa.test.REST_Assure_Get_Call -->
